version: "2"
services:
    web:
        build: .
        ports:
        - "8080:8080"
        depends_on:
        - mongo
        command: npm start
    mongo:
        image: mongo
        ports:
        - "27017:27017"

